ToDo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('firstpage/', include("firstpage.urls")),
    path('tasks/', include("tasks.urls"))
]

firstpage/urls.py
from django.urls import path
from . import views 

app_name = "firstpage"
urlpatterns = [
    path("<str:name>", views.index, name="index")
]

tasks/urls.py
from django.urls import path
from . import views 

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

firstpage/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

firstpage/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request, name):
    return render(request, "firstpage/index.html", {
        "name" : name.capitalize()
    })

tasks/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

# Create your views here.


def index(request):

    # Check if there already exists a "tasks" key in our session

    if "tasks" not in request.session:

        # If not, create a new list
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })


# Add a new task:
def add(request):
    if request.method == "POST":

        # Take in the data the user submitted and save it as form
        form = NewTaskForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the task from the 'cleaned' version of form data
            task = form.cleaned_data["task"]

            # Add the new task to our list of tasks
            request.session["tasks"] += [task]

            # Redirect user to list of tasks
            return HttpResponseRedirect(reverse("tasks:index"))
        else:

            # If the form is invalid, re-render the page with existing information.
            return render(request, "tasks/add.html", {
                "form": form
            })

    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

firstpage/templates/firstpage/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello</title>
        <link rel="stylesheet" href="{% static 'firstpage/styles.css' %}">
        <style>
            a:link, a:visited {
                background-color: #f44336;
                color: white;
                padding: 14px 25px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
            }

            a:hover, a:active {
                background-color: red;
                
                
            }
            </style>
    </head>
    <body style="background-color:mediumaquamarine;">
        
        <h1>Hello, {{ name }}!</h1>
        <p align="center"><a href="{% url 'tasks:index' %}">View Tasks</a></p>
        
    </body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <body style="background-color:powderblue;">
        <h1>ADD TASK:</h1>
        <form action="{% url 'tasks:add' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
        <a href="{% url 'tasks:index' %}">View Tasks</a>
    </body>

{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}
{% load static %}

{% block body %}
    <body style="background-color:powderblue;">
        <h2 style="margin-top:40px;" class="text-center">YOUR TASKS</h2>
        
        
        <ul>
            {% for task in tasks %}
              <li>{{ task }}</li>
            {% endfor %}
        </ul>
       
        <a href="{% url 'tasks:add' %}">Add a New Task</a>
        <a href="{% url 'firstpage:index' %}">Home</a> 
        
        
        
    </body>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
        <style>
            a:link, a:visited {
                background-color: #f44336;
                color: white;
                padding: 10px 20px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
            }

            a:hover, a:active {
                background-color: red;
                
                
            }
        </style>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>